import type { MetadataRoute } from 'next'

/**
 * robots.txt — generated by Next.js App Router.
 *
 * Why we explicitly allow AI crawlers:
 *  AI search (Google AI Overviews, ChatGPT, Perplexity, Bing Copilot, Claude)
 *  is the new front door for niche queries like "best tile cutter UK". If we
 *  block these crawlers we don't get cited. Citation = referral traffic.
 *
 * Bots explicitly allowed (named for clarity even though `*` already covers them):
 *  - GPTBot / ChatGPT-User / OAI-SearchBot — OpenAI / ChatGPT search.
 *  - Google-Extended — Google's AI training crawler (separate from Googlebot).
 *  - PerplexityBot / Perplexity-User — Perplexity AI.
 *  - ClaudeBot / Claude-Web / anthropic-ai — Anthropic.
 *  - Applebot-Extended — Apple Intelligence.
 *  - Bytespider — TikTok / ByteDance.
 *  - cohere-ai — Cohere.
 *
 * Bot blocked: AhrefsBot — saves bandwidth on a competitor's analytics tool.
 *
 * /go/ is disallowed for everyone — those are affiliate redirects, not content,
 * and indexing them hurts both SEO and our affiliate network compliance.
 */
export default function robots(): MetadataRoute.Robots {
  const aiCrawlers = [
    'GPTBot',
    'ChatGPT-User',
    'OAI-SearchBot',
    'Google-Extended',
    'PerplexityBot',
    'Perplexity-User',
    'ClaudeBot',
    'Claude-Web',
    'anthropic-ai',
    'Applebot-Extended',
    'Bytespider',
    'cohere-ai',
    'Meta-ExternalAgent',
    'Amazonbot',
    'DuckAssistBot',
  ]

  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/api/', '/_next/', '/go/'],
      },
      ...aiCrawlers.map((bot) => ({
        userAgent: bot,
        allow: '/',
        disallow: ['/api/', '/_next/', '/go/'],
      })),
      {
        userAgent: 'AhrefsBot',
        disallow: '/',
      },
    ],
    sitemap: 'https://tileflowuk.com/sitemap.xml',
    host: 'https://tileflowuk.com',
  }
}
